version: "3.7"

services:
  mongo:
    image: mongo
    container_name: 'orders_db'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=ecbd
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017-27019:27017-27019'